from pathlib import Path
ROOT=Path('.')
def read(path):return (ROOT/path).read_text(encoding='utf-8-sig')
def write(path,text):(ROOT/path).write_text(text,encoding='utf-8')
def replace(s,a,b):
 assert s.count(a)==1,(a[:90],s.count(a))
 return s.replace(a,b)
def section(s,a,b,body):
 start=s.index(a);end=s.index(b,start);return s[:start]+body+s[end:]
p='src/server/Services/MapService.luau';s=read(p)
s=replace(s,'local CartoonArt = require(ReplicatedStorage.Shared.Config.CartoonArt)\nlocal SignTheme = require(ReplicatedStorage.Shared.SignTheme)','local WorldSignModel = require(ReplicatedStorage.Shared.WorldSignModel)')
s=section(s,'-- offset is in world space,','local function bounds','')
s=section(s,'\tlocal surface = Instance.new("SurfaceGui")','\nend\n\n-- Vaults:', '\tWorldSignModel.Attach("SafeZone", paint, Enum.NormalId.Top)')
s=section(s,'\t\t\t\t-- The art-pack collect board','\t\t\t\tcashPads[slot] = cashPad', '''\t\t\t\tlocal padArt = block(`CashPadArt{slot}`, Vector3.new(2.6, 0.05, 5.6), cashPad.CFrame * CFrame.new(0, 0.04, 0), NAVY, levelFolder)
\t\t\t\tpadArt.CanCollide, padArt.CanTouch, padArt.CanQuery = false, false, false
\t\t\t\tlocal _, amountFace = WorldSignModel.Attach("CollectPad", padArt, Enum.NormalId.Top)
\t\t\t\tlocal padGui = WorldSignModel.Surface(padArt, amountFace, "Art", 70)
\t\t\t\tlocal padText = WorldSignModel.LiveText(padGui, "Amount", "$0", Color3.fromRGB(25, 57, 35))
''')
s=section(s,'\t\tlocal sign = label(','\n\t\t-- The Haunted Wheel:', '''\t\tlocal _, ownerFace = WorldSignModel.Attach("VaultOwner", signPart, Enum.NormalId.Back)
\t\tlocal sign = WorldSignModel.LiveText(WorldSignModel.Surface(signPart, ownerFace, "OwnerGui", 160), "Owner", "Empty Vault", color)
''')
s=section(s,'\t\tlocal signGui = Instance.new("SurfaceGui")','\t\tupgradeSign.Parent = folder', '''\t\tlocal _, upgradeFace = WorldSignModel.Attach("UpgradeBase", signBoard, Enum.NormalId.Back)
\t\tlocal signGui = WorldSignModel.Surface(signBoard, upgradeFace, "Gui", 80)
\t\tlocal content = Instance.new("Frame")
\t\tcontent.Name, content.BackgroundTransparency = "Content", 1
\t\tcontent.Position, content.Size = UDim2.fromScale(0.27, 0.12), UDim2.fromScale(0.68, 0.76)
\t\tcontent.Parent = signGui
''')
s=replace(s,'Vector3.new(6, 1.6, 0.4), at(wheelCenter.X, 15.2, wheelCenter.Z)','Vector3.new(6, 2.4, 0.4), at(wheelCenter.X, 15.2, wheelCenter.Z)')
s=replace(s,'\t\tlocal treadmillSign = label(wheelSign, "Creaky Wheel", color, UDim2.fromScale(9, 2), Vector3.new(0, 0.2, 1)) -- under the vault\'s own sign','\t\tlocal _, tierFace = WorldSignModel.Attach("HauntedWheel", wheelSign, Enum.NormalId.Back)\n\t\tlocal treadmillSign = WorldSignModel.LiveText(WorldSignModel.Surface(wheelSign, tierFace, "TierGui", 100), "Tier", "Creaky Wheel", color)')
write(p,s)
p='src/server/Services/BaseService.luau';s=read(p)
s=replace(s,'local SignTheme = require(ReplicatedStorage.Shared.SignTheme)','local SignTheme = require(ReplicatedStorage.Shared.SignTheme)\nlocal WorldSignModel = require(ReplicatedStorage.Shared.WorldSignModel)')
s=replace(s,'\tbase.SignPart.CFrame = base.Frame * CFrame.new(0, built.BackHeight + 2.4, -22)','\tbase.SignPart.CFrame = base.Frame * CFrame.new(0, built.BackHeight + 2.4, -22)\n\tWorldSignModel.MoveAttached(base.SignPart)')
s=section(s,'\tlocal gui = Instance.new("SurfaceGui")\n\tgui.Face = Enum.NormalId.Front','\tlocal click = Instance.new("ClickDetector")', '''\tlocal _, sellFace = WorldSignModel.Attach("SellSign", board, Enum.NormalId.Front)
\tlocal gui = WorldSignModel.Surface(board, sellFace, "Gui", 60)
\tlocal price = math.floor(Items.Income(item) * GameConfig.SellSeconds)
\tlocal label = WorldSignModel.LiveText(gui, "SalePrice", `Sell {Format.Cash(price)}`, Color3.fromRGB(25, 57, 35))
''')
write(p,s)
p='src/server/Services/ShopNPCs.luau';s=read(p)
s=replace(s,'local ToyBlockModel = require(ReplicatedStorage.Shared.ToyBlockModel)','local ToyBlockModel = require(ReplicatedStorage.Shared.ToyBlockModel)\nlocal WorldSignModel = require(ReplicatedStorage.Shared.WorldSignModel)')
s=section(s,'\t-- One clean title floating','\t-- Wares', '''\tlocal anchor = block(folder, "TitleAnchor", Vector3.new(12, 4, 0.25), at(0, 12.5, -1), spec.Color)
\tanchor.CanCollide, anchor.CanQuery, anchor.CanTouch = false, false, false
\tWorldSignModel.Attach(if spec.Panel == "Shop" then "ShopMortimer" else "ShopVesper", anchor, Enum.NormalId.Front)
''')
write(p,s)
p='src/server/Services/Rewards.luau';s=read(p)
needle='local ReplicatedStorage = game:GetService("ReplicatedStorage")';s=replace(s,needle,needle+'\nlocal WorldSignModel = require(ReplicatedStorage.Shared.WorldSignModel)')
s=section(s,'\t-- "FREE!" floats over it;','\tlocal prompt = Instance.new("ProximityPrompt")', '''\tlocal plaque = Instance.new("Part")
\tpla que
'''.replace('\tpla que\n', '''\tplaque.Name, plaque.Size = "FreeChestSign", Vector3.new(8, 5, 0.2)
\tplaque.CFrame = root.CFrame * CFrame.new(0, 6.5, 0)
\tplaque.Anchored, plaque.CanCollide, plaque.CanQuery, plaque.CanTouch = true, false, false, false
\tplaque.Parent = chest
\tlocal _, liveFace = WorldSignModel.Attach("FreeChestLabel", plaque, Enum.NormalId.Front)
\tWorldSignModel.LiveText(WorldSignModel.Surface(plaque, liveFace, "FreeLabel", 160), "Text", "FREE!", Color3.fromRGB(120, 255, 140))
'''))
write(p,s)
p='src/server/Services/ManorDecor.luau';s=read(p)
needle='local ToyBlockModel = require(ReplicatedStorage.Shared.ToyBlockModel)';s=replace(s,needle,needle+'\nlocal WorldSignModel = require(ReplicatedStorage.Shared.WorldSignModel)')
s=replace(s,'\tfor _, face in { Enum.NormalId.Front, Enum.NormalId.Back } do\n\t\tlocal gui = Instance.new("SurfaceGui")','\tlocal _, frontFace = WorldSignModel.Attach("EventBoard", board, Enum.NormalId.Front)\n\tlocal backAnchor = board:Clone()\n\tbackAnchor:ClearAllChildren()\n\tbackAnchor.Name, backAnchor.Parent = "EventBoardBack", board\n\tlocal _, backFace = WorldSignModel.Attach("EventBoard", backAnchor, Enum.NormalId.Back)\n\tfor _, face in { Enum.NormalId.Front, Enum.NormalId.Back } do\n\t\tlocal gui = Instance.new("SurfaceGui")\n\t\tgui.Adornee = if face == Enum.NormalId.Front then frontFace else backFace')
s=replace(s,'\t\tgui.Name = `Lines{face.Name}`\n\t\tgui.Face = face','\t\tgui.Name = `Lines{face.Name}`\n\t\tgui.Face = Enum.NormalId.Back')
write(p,s)
print('Integrated collect, sell, upgrade, owner, wheel, shops, chest, safe zone and event board')
