"""Persist the complete UI mockup and world-reference request before generation."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'assets/visual-expansion';OUT.mkdir(parents=True,exist_ok=True)
screens={
'KnifeIndex':'Knife Index, Common/Rare/Epic/Legendary/Mythic/Godly/Celestial/Cosmic filter tabs; a 6-column desktop or 5-column phone grid of knife cards. Discovered cards use supplied voxel knives. Undiscovered cards use the same dark knife silhouettes and native text "???", with EVERY blade, guard and pommel entirely inside its card. Show collection progress, Claim reward, and close X.',
'More':'More menu with exactly five large distinct tiles: Knives, Players, Powers, Rebirth, Stats. Their icons match the supplied knife, purple heads, yellow bolt, cyan arrows and gold trophy.',
'Unbox':'Unbox reel: a wide horizontal moving row of six rarity-coloured cards, each with an existing knife and a stepped rarity glow. Central gold top/bottom pointer identifies a Legendary Golden Dagger. Header "OPENING LEGENDARY CASE", odds strip, and reveal area "Golden Dagger" / "Legendary". No new illustration.',
'ShopCaseShop':'Mortimer Case Shop: existing rarity chest icons, native cash prices, Buy buttons and clearly readable odds. Four case cards per row desktop; three phone. Health upgrade uses Upgrades arrow, native max-health label and a buy button. Native header "CASE SHOP".',
'StoreCases':'Store, active Cases tab; tabs "Cases", "Lucky Blocks", "Passes", "Boosts". Featured Cosmic case, smaller other rarity cases, Robux prices as text and visible odds. Existing case icons only.',
'StoreLuckyBlocks':'Store with active Lucky Blocks tab and the same four tabs. Existing Rare through Cosmic question-mark cubes on seven shop cards. Prices as text and odds strip visible.',
'StorePasses':'Store with active Passes tab. VIP card uses existing gold trophy; Titan card uses existing up arrow; Knife Effects card uses existing knife; extra earnings card uses existing Cash icon. Native descriptions and Robux Buy buttons. Do not invent new pass illustrations.',
'StoreBoosts':'Store with active Boosts tab. Speed, cash and income/heat boost cards use only Speed shoe, Cash stack and Heat flame. Native duration labels and Buy buttons. No new icon shapes.',
'Upgrades':'Upgrades menu. Speed, Vault walls, Mounts/Slots and Health rows with existing Upgrades/Speed icons, native levels/prices, progress bars, and Upgrade buttons. A clean explanation of the next floor unlock. No unique house or wall illustration.',
'LuckyWheel':'Lucky Wheel screen: existing Hud.Spin multicolour wheel enlarged centrally, native reward labels around it, yellow pointer, remaining free spin text, Spin primary button, chance strip and close button. Any pointer/marker uses simple native geometry. No new prizes.',
'MysteryMerchant':'Mystery Merchant screen: existing Merchant striped tent icon in header, three featured knife cards, countdown "RESTOCKS IN 04:32", native prices and Buy buttons. Existing knife assets only.',
'GiftPicker':'Gift picker modal over Store: native heading "SEND A GIFT", list of players represented by existing purple voxel head icon, current selected gift shown with an existing case or knife, price and Send gift / Cancel. No new gift box image.',
'Powers':'Innocent Powers screen: Vanish, Radar, Bear Trap, Shield, Decoy, Flash, Barricade, Mimic cards. All power cards use the EXISTING yellow voxel Powers lightning icon; labels/descriptions provide differences. Show loadout slots, Equip/Upgrade buttons and levels. No ability-specific new illustrations.',
'Rebirth':'Rebirth screen: existing cyan voxel arrow-loop icon large, current/next rebirth benefits in native text, cash requirement/progress, Rebirth primary button and Cancel.',
'Stats':'Stats screen: existing gold trophy, native income/cash/heat/steals/wins/playtime rows, settings blue gear and native menu blur toggle. Clean two-column layout.',
'Players':'Players screen: native player names with existing purple voxel heads, Gift button, Team up / Leave team and Trade actions. Friend bonus banner "+10% cash per friend". No avatar portraits or custom logos.',
'Trade':'Trade screen: two side-by-side offer panels labelled "Your offer" and "Their offer", existing knife icon cards entirely inside each offer grid, player head icons, Ready / Cancel, native status "Waiting for both players" and confirmation countdown.',
'WelcomeDaily':'Welcome / daily streak: "WELCOME BACK" header, native offline earnings and Claim button, seven daily reward cards using existing Cash/chest/knife art, current day highlighted, streak counter. No new reward art.',
'MainHud':'Main gameplay HUD over a simple softly muted voxel plaza backdrop: left Shop/Index/More nav, right Free chest/Upgrades/Spin/Merchant column, top timer "MURDER ROUND IN 00:42", Speed/Cash/Heat chips with existing icons, Murderer chance icon+text, bottom Health and Energy bars with native labels only. Phone thumbstick bottom left and jump-control zone bottom right are clearly reserved and unobstructed. All icons distinct silhouettes.',
'RevealMurderer':'Round role reveal overlay over subdued plaza background. Exact native title "YOU ARE THE MURDERER", red stepped panel accent, existing large voxel knife icon, role instruction and equipped knife card. Same frame kit, no new character illustration.',
'RevealInnocent':'Round role reveal overlay. Exact title "YOU ARE INNOCENT", cyan/green stepped panel accent, existing purple voxel heads icon and yellow Powers bolt, survival instruction and at-risk knife card. Same frame kit, no new character illustration.',
'RoundResults':'Round results screen: native title "ROUND RESULTS", existing gold trophy, winner names and rewards in native text, survivor rows with existing purple heads, any stolen knife shown using existing knives, Continue button. No new victory illustration.',
'ToastsAnnouncements':'Main HUD with a compact stack of three notification toasts using existing Cash, Heat and knife icons, plus a top native-text announcement banner. Messages: "Knife deposited", "+$12.4K collected", "A rare knife appeared!". Use existing stepped frames, native text, no one-off art.'
}
kit='Use case: ui-mockup. Full-screen high-fidelity Roblox game UI rebuild reference. Match the supplied art EXACTLY: chunky voxel toys, near-black outlines, vivid flat colours, stepped navy/cyan panel edges and square studs, top-left highlights. This is a clean front-on UI screenshot, not a 3D diorama. ONLY use imagery from the supplied existing icon/knife/frame sheets and the stated reusable assets; all other elements are native text, flat fills, rectangles, bars or simple markers. NO new mascots, portraits, specialty icons, decorations or one-off art. Clear white chunky rounded lettering with dark stroke. Use plain labels that Claude can recreate in Luau. Keep text legible, preserve full knife padding, never crop icons. '
refs=['assets/voxel-ui/review/Hud.png','assets/voxel-ui/review/Knives.png','assets/voxel-ui/review/Frames.png','assets/voxel-ui/review/Cases.png','assets/voxel-ui/review/LuckyBlocks.png']
jobs=[]
worlds={
'UpgradeBase':'A chunky voxel Upgrade Base board on a small two-post easel: cyan/navy stepped physical frame, raised block-built mint/ivory house with yellow roof on its LEFT, plain navy cuboid text face on its RIGHT. Blank live text area; no images, printed text, textures or smooth panels. Sized to a 9 x 3.4 stud board.',
'CollectPad':'A physical mint-green voxel pill lying on a floor, chunky violet outline, tiered stepped corners and small square studs. Plain mint cuboid top face for one live amount. Footprint 5.6 x 2.6 studs and 0.35 stud thickness. No written text or image decal.',
'SellSign':'A small standing orange/green voxel pill sign on a chunky navy A-frame/easel, leaning back 18 degrees. Stepped corners, thick violet/navy outline, plain inset green cuboid face for a live Sell price. Size 4.6 x 1.5 studs. No text or images.',
'VaultOwner':'A navy/cyan stepped physical vault owner sign with squared bright corner caps and block-built VAULT header letters. Plain inner cuboid face for the live owner name. Fits 20 x 5 stud mount. No image textures or floating 2D panels.',
'HauntedWheel':'Block-built HAUNTED WHEEL title sign matching the dark navy/cyan toy wheel with amber accents: chunky block letters, dark backing cuboids, tiny wheel/cog voxel decoration, two physical mount brackets. All static words modelled as blocks. No image textures.',
'FreeChestLabel':'A compact physical voxel sign reading FREE CHEST in raised chunky white/gold block letters, navy/green stepped frame, small block sparkle and blank flat cuboid face below for a live cooldown. Matching the game gold voxel free chest; no printed images.',
'ShopMortimer':'Block-built 3D shop stall title reading KNIFE MERCHANT, raised ivory voxel letters on dark navy stepped frame, gold corner studs, and a small red-hilt silver voxel knife decoration. Matches chunky striped toy shop. No printed text or image textures.',
'ShopVesper':'Block-built 3D shop stall title reading INNOCENT POWERS, raised ivory voxel letters on dark violet stepped frame, pink/cyan square studs, and small yellow voxel lightning decoration. No printed text or image textures.',
'SafeZone':'Physical 3D SAFE ZONE raised ivory voxel letters on a plaza floor, shallow dark navy voxel letter outlines, mint/blue block shield decorations either side. Large readable 60 x 10 stud footprint. No sign panel, painted text or image textures.',
'EventBoard':'Large block-built navy/cyan event-board backing matching the toy plaza, deep layered rectangular beams, voxel-stepped corners, amber corner caps, square stud trim and a plain broad navy cuboid face for four live text lines. The same live text can show on both faces. Size 52 x 15 x 1.4 studs. No baked text, image textures or flat painted panel.'
}
for name,description in worlds.items():
    jobs.append(dict(Id='World.'+name,File='world-references/'+name+'.png',Size=None,References=[],Prompt='Use case: stylized-concept. Orthographic three-quarter Roblox voxel toy model reference, isolated on light grey background. Build everything visibly from crisp cuboid blocks, bright flat colours and near-black edges. '+description+' Physical geometry only, no bitmap artwork on faces. Show the entire object with padding.'))
for name,description in screens.items():
    for device,size in [('Desktop',[1920,1080]),('Phone',[2400,1080])]:
        prompt=kit+f' Output canvas {size[0]}x{size[1]}, {device.lower()} landscape. '+('Large desktop layout with balanced margins. ' if device=='Desktop' else 'Mobile landscape: big 44px-or-larger touch targets, compact text, safe left/right edge margins and bottom corner control exclusions; responsive layout, not a stretched desktop screen. ')+description
        jobs.append(dict(Id='Mockups.'+name+'.'+device,File='mockups/'+name+'-'+device.lower()+'.png',Size=size,References=refs,Prompt=prompt))
for job in jobs:(OUT/job['File']).parent.mkdir(parents=True,exist_ok=True)
(OUT/'jobs.json').write_text(json.dumps(dict(Workflow='Built-in ImageGen, one generated reference per world prop; one full-screen mockup per screen and device',Jobs=jobs),indent=2))
(OUT/'scope.json').write_text(json.dumps(dict(World='Replace all world panels/sign images with solid-colour voxel geometry; live values are text-only SurfaceGuis; preserve all interactive contracts and floating knife billboards',BossTitles='Original 16 PNGs remain design references only; new solid-colour voxel geometry must not use those textures in the world',UI='46 full-screen mockups covering 23 screen/state/tab layouts in desktop and phone landscape; 24 individual knife silhouettes; asset coverage must use the shared kit',ExistingArt='82 uploaded assets in assets/voxel-ui',Status='In progress'),indent=2))
print('Prepared',len(jobs),'generation jobs:',len(worlds),'world references and',len(screens)*2,'full-screen UI mockups')
